# Generated by Django 6.0.7 on 2026-08-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('curriculum', models.CharField(blank=True, max_length=255)),
                ('tipo_deseado', models.CharField(blank=True, choices=[('tutor', 'Tutor'), ('especialista', 'Especialista'), ('ambos', 'Ambos')], max_length=20)),
                ('materias', models.ManyToManyField(blank=True, related_name='candidatos', to='myapp.materia')),
            ],
        ),
    ]
