# Generated by Django 6.0.7 on 2026-08-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('disposicion', models.CharField(choices=[('no_localizado', 'No localizado'), ('no_interesado', 'No está interesado'), ('concertada', 'Entrevista concertada')], max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='myapp.candidato')),
            ],
        ),
    ]
