# Generated by Django 6.0.7 on 2026-08-21 19:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_llamada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valoracion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('llamada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrevista', to='myapp.llamada')),
                ('materia_a_cubrir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas', to='myapp.materia')),
            ],
        ),
    ]
